# Generated by Django 5.2.7 on 2025-10-04 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="habits.habit"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
