# Generated by Django 5.2.7 on 2025-10-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_checkin_habit_alter_habit_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
