# Generated by Django 5.2.7 on 2025-10-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_checkin_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
